//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ejemplo01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Provincia
    {
        public string idprovincia { get; set; }
        public string nomprovincia { get; set; }
    }
}
